!function(e,t){"object"==typeof exports&&"undefined"!=typeof module?module.exports=t(require("vue")):"function"==typeof define&&define.amd?define(["vue"],t):(e=e||self).VuePosterImage=t(e.Vue)}(this,(function(e){"use strict";e=e&&e.hasOwnProperty("default")?e.default:e;function t(e,t){var n,o,r,i,u={label:0,sent:function(){if(1&r[0])throw r[1];return r[1]},trys:[],ops:[]};return i={next:s(0),throw:s(1),return:s(2)},"function"==typeof Symbol&&(i[Symbol.iterator]=function(){return this}),i;function s(i){return function(s){return function(i){if(n)throw new TypeError("Generator is already executing.");for(;u;)try{if(n=1,o&&(r=2&i[0]?o.return:i[0]?o.throw||((r=o.return)&&r.call(o),0):o.next)&&!(r=r.call(o,i[1])).done)return r;switch(o=0,r&&(i=[2&i[0],r.value]),i[0]){case 0:case 1:r=i;break;case 4:return u.label++,{value:i[1],done:!1};case 5:u.label++,o=i[1],i=[0];continue;case 7:i=u.ops.pop(),u.trys.pop();continue;default:if(!(r=(r=u.trys).length>0&&r[r.length-1])&&(6===i[0]||2===i[0])){u=0;continue}if(3===i[0]&&(!r||i[1]>r[0]&&i[1]<r[3])){u.label=i[1];break}if(6===i[0]&&u.label<r[1]){u.label=r[1],r=i;break}if(r&&u.label<r[2]){u.label=r[2],u.ops.push(i);break}r[2]&&u.ops.pop(),u.trys.pop();continue}i=t.call(e,u)}catch(e){i=[6,e],o=0}finally{n=r=0}if(5&i[0])throw i[1];return{value:i[0]?i[1]:void 0,done:!0}}([i,s])}}}var n=function(e){return console.warn("[vue-poster]: "+e)};document.createElement("canvas").getContext("2d");function o(e,t){var o=new Image;return t&&(o.crossOrigin="anonymous"),new Promise((function(t){o.onload=function(){return t(o)},o.onerror=function(){return n("Failed to load image at "+e)},o.src=e}))}var r=function(e,n,r){return i=void 0,u=void 0,a=function(){var n,i,u,s,a,c,f,d,l,p,h;return t(this,(function(t){switch(t.label){case 0:return n=e.width,i=e.height,u=e.offsetX,s=void 0===u?0:u,a=e.offsetY,c=void 0===a?0:a,f=e.src,d=e.cors,[4,o(f,void 0!==d&&d)];case 1:return l=t.sent(),p=n||l.width/1,h=i||l.height/1,r.drawImage(l,s,c,p,h),[2,new Promise((function(e){return e()}))]}}))},new((s=void 0)||(s=Promise))((function(e,t){function n(e){try{r(a.next(e))}catch(e){t(e)}}function o(e){try{r(a.throw(e))}catch(e){t(e)}}function r(t){t.done?e(t.value):new s((function(e){e(t.value)})).then(n,o)}r((a=a.apply(i,u||[])).next())}));
/*! *****************************************************************************
  Copyright (c) Microsoft Corporation. All rights reserved.
  Licensed under the Apache License, Version 2.0 (the "License"); you may not use
  this file except in compliance with the License. You may obtain a copy of the
  License at http://www.apache.org/licenses/LICENSE-2.0

  THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
  WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
  MERCHANTABLITY OR NON-INFRINGEMENT.

  See the Apache Version 2.0 License for specific language governing permissions
  and limitations under the License.
  ***************************************************************************** */
var i,u,s,a};var i=function(e,t,n,o,r,i,u,s,a,c){"boolean"!=typeof u&&(a=s,s=u,u=!1);var f,d="function"==typeof n?n.options:n;if(e&&e.render&&(d.render=e.render,d.staticRenderFns=e.staticRenderFns,d._compiled=!0,r&&(d.functional=!0)),o&&(d._scopeId=o),i?(f=function(e){(e=e||this.$vnode&&this.$vnode.ssrContext||this.parent&&this.parent.$vnode&&this.parent.$vnode.ssrContext)||"undefined"==typeof __VUE_SSR_CONTEXT__||(e=__VUE_SSR_CONTEXT__),t&&t.call(this,a(e)),e&&e._registeredComponents&&e._registeredComponents.add(i)},d._ssrRegister=f):t&&(f=u?function(){t.call(this,c(this.$root.$options.shadowRoot))}:function(e){t.call(this,s(e))}),f)if(d.functional){var l=d.render;d.render=function(e,t){return f.call(t),l(e,t)}}else{var p=d.beforeCreate;d.beforeCreate=p?[].concat(p,f):[f]}return n}({},void 0,e.extend({name:"poster-image",props:{width:Number,height:Number,offsetY:Number,offsetX:Number,src:String,cors:{type:Boolean,default:!1}},mounted:function(){var e,t,n,o,i=this;e="poster",t="on-poster-element-mounted",n=function(e,t){return r({width:i.width,height:i.height,offsetX:i.offsetX,offsetY:i.offsetY,src:i.src,cors:i.cors},0,t)},(o=(this.$parent.$children||[]).filter((function(t){return t.$options.name===e})))[0]&&o[0].$emit.apply(o[0],[t,n])},render:function(e){return e()}}),void 0,void 0,void 0,void 0,void 0);return"undefined"!=typeof window&&window.Vue&&e.component("poster-image",i),i}));
